#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. ~/.config/i3blocks/cores.conf

dir="${BLOCK_INSTANCE:-$HOME}"
uso=$(df -h -P -l "$dir" | awk 'NR==2{print $5}' | tr -dc '0-9')

if [[ ${uso} -gt 80 ]]; then
	cor=$vermelho
elif [[ ${uso} -gt 70 ]]; then
	cor=$cormed
elif [[ ${uso} -gt 60 ]]; then
	cor=$verde
else
	cor=""
fi

if [[ $BLOCK_BUTTON -eq 1 ]]; then
    mate-disk-usage-analyzer
fi

echo "${uso}%"
echo "${uso}%"
echo "$cor"
