#!/bin/bash

saida=$(curl -s "https://finance.google.com/finance?q=USDBRL" | \
grep -o '<span class=bld>.*</span>' | \
sed 's/\(<span class=bld>\|<\/span>\)//g' | \
tr -d '[:alpha:][:space:]' | awk '{printf("%.2f\n", $1)}')

echo "$saida"
echo "$saida"
echo ''
