#!/bin/bash

. ~/.config/i3blocks/cores.conf

case $BLOCK_BUTTON in
	1) notify-send "Data" "$(date '+%d/%m/%Y')" ;;  # left click, pause/unpause
	2) notify-send "Data" "$(date '+%A')" ;;  # middle click, show info
	3) notify-send "Data" "$(date '+%A')" ;;  # right click, gmpc
#    4) mpc prev | filter ;;  # scroll up, previous
#    5) mpc next | filter ;;  # scroll down, next
#    *) mpc current | filter ;;
esac

echo "$(date '+%H:%M')"
echo "$(date '+%H:%M')"
echo ""
