#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. ~/.config/i3blocks/cores.conf

tipo="${BLOCK_INSTANCE:-Mem}"

total=$(free -m | grep $tipo | awk '{print $2}')
usada=$(free -m | grep $tipo | awk '{print $3}')
por=$(echo "scale=2;(${usada}/${total})*100" | bc)
porc=$(echo "scale=0;$por/1" | bc)

if [[ ${porc} -gt 80 ]]; then
	cor=$vermelho
elif [[ ${porc} -gt 60 ]]; then
	cor=$cormed2
elif [[ ${porc} -gt 50 ]]; then
	cor=$verde
else
	cor=""
fi

if [[ $BLOCK_BUTTON -eq 1 ]]; then
    lxtask
fi

echo "${porc}%"
echo "${porc}%"
echo "$cor"

