#!/bin/bash

. ~/.config/i3blocks/cores.conf

slash=$(echo $(mpc current) | awk -F'/' '{print $2}')

if [[ -n "$slash" ]]; then
    saida=$(echo "$slash" | sed 'y/ãāáǎàçēêéěèīíǐìōóǒòūúǔùǖǘǚǜÃĀÁǍÀĒÉĚÈĪÍǏÌŌÓǑÒŪÚǓÙǕǗǙǛ/aaaaaceeeeeiiiioooouuuuuuuuAAAAAEEEEIIIIOOOOUUUUUUUU/')
else
    saida=$(echo "$(mpc current)" | sed 'y/ãāáǎàçēêéěèīíǐìōóǒòūúǔùǖǘǚǜÃĀÁǍÀĒÉĚÈĪÍǏÌŌÓǑÒŪÚǓÙǕǗǙǛ/aaaaaceeeeeiiiioooouuuuuuuuAAAAAEEEEIIIIOOOOUUUUUUUU/')
fi


filter() {
    if [ "$(mpc | grep "^\[playing\]" | awk '{print $1}')" = "[playing]" ];then
        if [ "$(mpc | head -1 | wc -c )" -lt 30 ];then
            echo -e "$saida"
            echo -e "$saida"
            echo ''
        else
            echo -e "$(echo $saida | head -1 | head -c 30)..."
            echo -e "$(echo $saida | head -1 | head -c 30)..."
            echo ''
        fi
    else
        echo ' MPD'
        echo ' MPD'
        echo ''
    fi
}

case $BLOCK_BUTTON in
	1) mpc toggle | filter ;;  # left click, pause/unpause
	2) notify-send "MPD" "$saida" | filter ;;  # middle click, show info
	3) gmpc | filter ;;  # right click, gmpc
    4) mpc prev | filter ;;  # scroll up, previous
    5) mpc next | filter ;;  # scroll down, next
    *) mpc current | filter ;;
esac
