#!/bin/bash

. ~/.config/i3blocks/cores.conf

TRASH_DIRECTORY="${BLOCK_INSTANCE}"
#TRASH_DIRECTORY="${HOME}/.local/share/Trash"
TRASH_TEMP="/tmp/lixo"

if [[ "${TRASH_DIRECTORY}" = "" ]]; then
  TRASH_DIRECTORY=${XDG_DATA_HOME:-"${HOME}/.local/share/Trash"}
fi

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xdg-open "${TRASH_DIRECTORY}/files"
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
	i3-sensible-terminal -e "rmlint -g ${HOME}"
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then

	if [ ! -d $TRASH_TEMP ]; then
		mkdir $TRASH_TEMP
	fi

	cp -rf ${TRASH_DIRECTORY}/files ${TRASH_TEMP}/
	cp -rf ${TRASH_DIRECTORY}/info ${TRASH_TEMP}/

	rm -rf ${TRASH_DIRECTORY}/files
	rm -rf ${TRASH_DIRECTORY}/info
	
	mkdir ${TRASH_DIRECTORY}/files
	mkdir ${TRASH_DIRECTORY}/info
fi

TRASH_COUNT=$(ls -U -1 "${TRASH_DIRECTORY}/files" | wc -l)

if [[ ${TRASH_COUNT} -gt 60 ]]; then
	cor=$vermelho
elif [[ ${TRASH_COUNT} -gt 40 ]]; then
	cor=$cormed
elif [[ ${TRASH_COUNT} -gt 20 ]]; then
	cor=$verde
else
	cor=''
fi

echo "${TRASH_COUNT}"
echo "${TRASH_COUNT}"
echo "$cor"

#if [[ "${TRASH_COUNT}" -ge "${URGENT_VALUE}" ]]; then
#  exit 33
#fi
